language: c
compiler: clang
install:
    - source ~/virtualenv/python3.5/bin/activate
    - pip install meson
# ok now I have to get a newer version of ninja than 1.3.1 which is the latest
# you can get from trusty *sigh*
    - curl -LO https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
    - unzip ninja-linux.zip ninja
    - export PATH=$PATH:.
addons:
    apt:
        packages:
            - libgdbm-dev

# man I wish I could get away with a container, but I currently need docker for compiling the vdso
sudo: required
services: docker

script:
    - meson build
    - ninja -C build
